using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class DamageNumber : MonoBehaviour
{
    public TextMeshProUGUI damageText;
    public float lifeTime;
    private float lifeCounter;
    public float Speed = 1f;

    // Update is called once per frame
    void Update()
    {
        if (lifeCounter > 0)
        {
            lifeCounter -= Time.deltaTime;
            if(lifeCounter <= 0)
            {
                Destroy(gameObject);
            }
        }
        transform.position += Vector3.up * Speed * Time.deltaTime;
    }
    public void Setup(int damageDisplay)
    {
        lifeCounter = lifeTime;
        damageText.text = damageDisplay.ToString();
    }
}
